<?php

$language['english'] = array(
  'HOME'            =>  'Home',
  'Welcome to TechMVC. You have successfully installed TechMVC.' =>  'Welcome to TechMVC. You have successfully installed TechMVC.',
  'LICENSE NOTICE'  =>  'TechMVC is licensed under MIT. Please read the license document before using TechMVC. You should have received a copy of the 
      MIT License along with TechMVC.  If not, see <a href="http://en.wikipedia.org/wiki/MIT_License">http://en.wikipedia.org/wiki/MIT_License</a>.',
   'FURTHER INFO'   =>  'For further details or help you can directly contact the developers at <a href="mailto:techmvc@googlegroups.com" title="Contact Developers Group">techmvc@googlegroups.com</a>. We will get back to you within 24hrs or may be less.',
);
