<?php

$language['spanish'] = array(
  'HOME'            =>  'Casa',
  'Welcome to TechMVC. You have successfully installed TechMVC.' =>  'Bienvenido a TechMVC. Usted ha instalado satisfactoriamente TechMVC.',
  'LICENSE NOTICE'  =>  'TechMVC está licenciado bajo MIT. Por favor, lea el documento de licencia antes de utilizar TechMVC. Debería haber recibido una copia de la
      MIT License junto con TechMVC. Si no, ver <a href="http://en.wikipedia.org/wiki/MIT_License"> http://en.wikipedia.org/wiki/MIT_License </a>.',
   'FURTHER INFO'   =>  'Para mayor información o ayuda puede contactar directamente con los desarrolladores de  <a href="mailto:techmvc@googlegroups.com" title="Contact Developers Group">  techmvc@googlegroups.com </a>. Nos pondremos en contacto con usted dentro de 24 horas o puede ser menos.',
);
